name: Client Pull Request Tests

on:
  pull_request:
    branches: [master]
    paths: ["ElvargClient/**"]

jobs:
  build:
    name: Run client tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: 'gradle'

    - name: Build client
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: ElvargClient
